name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Depth 0 required for branch-based versioning
      - name: Test
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            10.0
      - name: Run unit tests
        run: |
          dotnet build tests/Api.Tests/Api.Tests.csproj
          dotnet test --test-modules tests/Api.Tests/bin/Debug/net10.0/Api.Tests.dll --no-build
      - name: Run integration tests
        run: |
          docker compose up -d
          dotnet build tests/Api.IntegrationTests/Api.IntegrationTests.csproj
          dotnet test --test-modules tests/Api.IntegrationTests/bin/Debug/net10.0/Api.IntegrationTests.dll --no-build
      - name: Docker Compose Logs
        if: always()
        run: |
          docker compose logs
      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  sonarcloud-scan:
    name: CDP SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    needs: build
    secrets: inherit
